// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDON-iaKD4yONPTrFcqt5gawNhPyA9tVng',
    appId: '1:104287385697:web:3feaec5f8e0ffcae9d9220',
    messagingSenderId: '104287385697',
    projectId: 'nutrition-app-7726b',
    authDomain: 'nutrition-app-7726b.firebaseapp.com',
    storageBucket: 'nutrition-app-7726b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8GBvCzK1CCJtJSkdkaxaJeamRC-s5FA',
    appId: '1:104287385697:android:777d119477c8b7fa9d9220',
    messagingSenderId: '104287385697',
    projectId: 'nutrition-app-7726b',
    storageBucket: 'nutrition-app-7726b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRCMZNopteFqw7AcI5y9U2nRKAs8Cg5c',
    appId: '1:104287385697:ios:857bad0e8831bfb99d9220',
    messagingSenderId: '104287385697',
    projectId: 'nutrition-app-7726b',
    storageBucket: 'nutrition-app-7726b.firebasestorage.app',
    iosBundleId: 'com.example.fitvioraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRCMZNopteFqw7AcI5y9U2nRKAs8Cg5c',
    appId: '1:104287385697:ios:857bad0e8831bfb99d9220',
    messagingSenderId: '104287385697',
    projectId: 'nutrition-app-7726b',
    storageBucket: 'nutrition-app-7726b.firebasestorage.app',
    iosBundleId: 'com.example.fitvioraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDON-iaKD4yONPTrFcqt5gawNhPyA9tVng',
    appId: '1:104287385697:web:7b51b62d5fc6e5909d9220',
    messagingSenderId: '104287385697',
    projectId: 'nutrition-app-7726b',
    authDomain: 'nutrition-app-7726b.firebaseapp.com',
    storageBucket: 'nutrition-app-7726b.firebasestorage.app',
  );

}